-- Degree and Teaching in Same School
SELECT DISTINCT PROFESSOR_KEY, DEGREE_SCHOOL_STD, TITLE
from Biography
WHERE Title LIKE '%'||DEGREE_SCHOOL||'%'
ORDER BY PROFESSOR_KEY;

-- PHD Percent Grouped by School
SELECT 
    DEGREE_SCHOOL_STD,
	COUNT(DISTINCT CASE WHEN DEGREE LIKE '%Ph.D.%' THEN PROFESSOR_KEY END) AS NO_OF_PROFESSORS_WITH_DEGREE,
	COUNT(DISTINCT PROFESSOR_KEY) AS NO_OF_DISTINCT_PROFESSOR_AT_UNI,
    ROUND(COUNT(DISTINCT CASE WHEN DEGREE LIKE '%Ph.D.%' THEN PROFESSOR_KEY END) * 100.0/ COUNT(DISTINCT PROFESSOR_KEY), 2) AS PHD_PERCENT
FROM Biography
GROUP BY DEGREE_SCHOOL_STD
HAVING PHD_PERCENT > 0
ORDER BY PHD_PERCENT DESC;

-- DISTINCT Experience
SELECT DISTINCT EXPERIENCE from subject;

-- Checking
select * from
Biography b join School s
on b.professor_key = s.professor_key JOIN
subject sj on sj.professor_key = s.professor_key
where b.professor_key = "James H. Barnett Jr.";

-- What % of Schools offer x Course
SELECT SU.SUBJECT,
ROUND((COUNT(SC.SCHOOL) * 100.0) /(SELECT COUNT(DISTINCT SCHOOL) FROM SCHOOL), 2) AS PERCENTAGE_OF_SCHOOLS_OFFERING_PARTICULAR_SUBJ
FROM
SCHOOL SC JOIN SUBJECT SU 
ON SC.PROFESSOR_KEY = SU.PROFESSOR_KEY
GROUP BY SU.SUBJECT
ORDER BY PERCENTAGE_OF_SCHOOLS_OFFERING_PARTICULAR_SUBJ DESC;